### ISSUE TITLE
Mobile Navbar button does not work, navbar is expanded by default.

### ISSUE THREAD

**Issue by GasimoCodes** [filipecarneiro/hugo-bootstrap-theme#1]
The mobile navbar expansion button does not do anything on the master branch samle site.

Found on 
Windows Firefox
Windows Edge
Android Firefox. 

Tested on both compiled exampleSite (following the docs) and the [live demo site](https://filipecarneiro.github.io/hugo-bootstrap-theme/).

**Comment by filipecarneiro** [comment]
I've missed the import of bootstrap/transitions in main.scss

See Bootstrap customize SASS option B (Include parts of Bootstrap):
https://getbootstrap.com/docs/5.3/customize/sass/
