### ISSUE TITLE
Suggestion: Put footer at bottom of page even when litlle page content

### ISSUE THREAD

**Issue by GasimoCodes** [filipecarneiro/hugo-bootstrap-theme#2]
On the following example, the page content is not big enough to push footer off-site. The body content height should be at least of a size which would put the offset perfectly at the page bottom. This can be done in purely in sass. 

![image](https://github.com/filipecarneiro/hugo-bootstrap-theme/assets/22917863/b9cf6571-4aaa-4206-a497-13462e7f8c91)

**Comment by filipecarneiro** [comment]
Use [Bootstrap position utility](https://getbootstrap.com/docs/5.3/utilities/position/) `fixed-bottom`? Need to test...

**Comment by filipecarneiro** [comment]
I prefer this option [How to Make Footer Stay at Bottom of Page with Bootstrap](https://radu.link/make-footer-stay-bottom-page-bootstrap/) to vertical align the footer to the bottom of the page (on pages with little content).
