### ISSUE TITLE
Post images dont scale, causing the page to expand in the demo. 

### ISSUE THREAD

**Issue by GasimoCodes** [filipecarneiro/hugo-bootstrap-theme#3]
Large post images dont scale properly, causing the site to grow horizontally

![image](https://github.com/filipecarneiro/hugo-bootstrap-theme/assets/22917863/f39ae172-cd17-4f84-b7eb-7f78edc3c794)

**Comment by filipecarneiro** [comment]
Need to make images responsive in markdown content with `.img-fluid`. This applies `max-width: 100%`; and `height: auto`;
