### ISSUE TITLE
add missing dependency hugo-installer

### ISSUE THREAD

**Issue by northben** [filipecarneiro/hugo-bootstrap-theme#4]
I followed the instructions for a new website and got the following error.

```
npm ERR! code 127
npm ERR! path /Users/x/projects/y/node_modules/@filipecarneiro/hugo-bootstrap-theme
npm ERR! command failed
npm ERR! command sh -c hugo-installer --version otherDependencies.hugo --extended
npm ERR! sh: hugo-installer: command not found

npm ERR! A complete log of this run can be found in: /Users/x/.npm/_logs/2024-01-17T22_56_36_356Z-debug-0.log
```

solution: `npm install hugo-installer`

**Comment by northben** [comment]
update: I found it was easier to clone the repo and copy the exampleSite directory to get started, and then it wasn't necessary to have npm or node installed at all.

**Comment by filipecarneiro** [comment]
`npm ERR! code 127`

This usually occurs when installing an outdated npm module which is not compatible with the current Node version on your system.

To diagnose this, run:

```
npm --version
node --version
```

Then follow [this instructions](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) to install the latest versions. Or just try `npm install npm@latest -g`.

If you install Hugo globally, you don't need NPM but, using NPM will give you some cool features, especially if your project is in a CI/CD pipeline. With the package `hugo-installer` you don't have to preinstall Hugo on your build server. Also, you can use packages like `netlify-cli`, `postcss`, `cssnano` and other packages for automated tests.
