### ISSUE TITLE
email shortcode do not work

### ISSUE THREAD

**Issue by geraldraaf** [filipecarneiro/hugo-bootstrap-theme#6]
i am testing "Hugo Bootstrap Theme"

i recognized that the shortcode email doesn't work i do not display a email address

{{< email user="jsmith" domain="example.com" class="cool-link" >}}

the code from tel works as expected and display a phone number

beside of that great work

**Comment by geraldraaf** [comment]
I have added the string 'nonce......' to the file "node_modules/@filipecarneiro/hugo-bootstrap-theme/layouts/partials/head/content-security-policy.html" and now it works.
Thank you

**Comment by filipecarneiro** [comment]
Hi,

Please don't do that! If you run `npm install` to update your packages, you will lose your changes...
Also, `node_modules` folder should be excluded from your repository.

You should [override the template file](https://gohugobrasil.netlify.app/themes/customizing/#override-template-files). Just create a file with the same name in your `layouts` folder: `/layouts/partials/head/content-security-policy.html` and add you changes there.
