### ISSUE TITLE
Question start/home page problem

### ISSUE THREAD

**Issue by geraldraaf** [filipecarneiro/hugo-bootstrap-theme#7]
Hi,

I thought i create _index.md in the content folder, as main/start/home page, but it doesn't work as expected. The content is far left.
did i do something wrong or is this normal behaviour. i take 2 screenshots to show what i mean.
can you give me a hint how i can correct this

**i thought the page should look like this**

![screenshot-1](https://github.com/filipecarneiro/hugo-bootstrap-theme/assets/1211289/66184d35-3e35-4f76-b79f-d01b064fd1f0)

**but it's like this screenshot**

![screenshoot-2](https://github.com/filipecarneiro/hugo-bootstrap-theme/assets/1211289/a3c5f019-1a20-4e3f-bed6-ba24ff4fc15e)

**Comment by geraldraaf** [comment]
i did complete new install, and run diff over the directories.

**Comment by geraldraaf** [comment]
forgot to close

**Comment by filipecarneiro** [comment]
Probably, in that index.html, you forgot the `container` `div`.
See: https://getbootstrap.com/docs/5.3/layout/containers/#default-container
